### PR TITLE
1.0.1 - Krypton standards

### PR DESCRIPTION
**Pull request by aureliencousin**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Any chance you can submit this to Kodi repo? Also add the 2018 videos? :)

**Comment by aureliencousin** [comment]
Hi Martijn ! Thank you for your interest in HardstyleTV. There you go:
https://github.com/xbmc/repo-plugins/pull/2111

Le sam. 13 oct. 2018 à 10:55, Martijn Kaijser <notifications@github.com> a
écrit :

**Comment by aureliencousin** [comment]
> Any chance you can submit this to Kodi repo? Also add the 2018 videos? :)

As travis wasn't happy with my previous PR, here's the updated one: https://github.com/xbmc/repo-plugins/pull/2112

**Comment by MartijnKaijser** [comment]
Thx

**Pull request merged**
